# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_declarations: true
    prefer_const_constructors: true
    always_declare_return_types: true
    require_trailing_commas: true
    avoid_print: true
    unawaited_futures: true
    prefer_final_locals: true
    prefer_single_quotes: true

formatter:
  trailing_commas: preserve

analyzer:
  exclude:
    - packages/flutter-quill/**
    - build/**
    - lib/**/*.g.dart
  errors:
    missing_return: error
    dead_code: error
    unused_element: warning
    unused_import: warning
    unused_local_variable: warning
