// GENERATED FILE - DO NOT MODIFY
// This file is auto-generated by bin/update_app_logo
// To add or remove logos, modify the script or update assets/logos/ directory

import 'package:storypad/gen/assets.gen.dart';

enum AppLogo {
  arcticons_diary(logoName: 'arcticons_diary'),
  bi_journal_bookmark_fill(logoName: 'bi_journal_bookmark_fill'),
  famicons_journal(logoName: 'famicons_journal'),
  fluent_animal_cat_24_filled(logoName: 'fluent_animal_cat_24_filled'),
  iconoir_journal(logoName: 'iconoir_journal'),
  mdi_fruit_grapes(logoName: 'mdi_fruit_grapes'),
  mingcute_apple_fruit_fill(logoName: 'mingcute_apple_fruit_fill'),
  ooui_journal_ltr(logoName: 'ooui_journal_ltr'),
  streamline_ultimate_fruit_banana(logoName: 'streamline_ultimate_fruit_banana'),
  uil_diary_alt(logoName: 'uil_diary_alt')
  ;

  final String logoName;

  String get xcodeLogoName => logoName;
  String get androidActivityAliasName => 'com.tc.writestory.$logoName';

  bool get free => this == AppLogo.values.first;

  const AppLogo({
    required this.logoName,
  });

  AssetGenImage get asset {
    switch (this) {
      case .arcticons_diary:
        return Assets.logos.arcticonsDiary.assets.arcticonsDiary;
      case .bi_journal_bookmark_fill:
        return Assets.logos.biJournalBookmarkFill.assets.biJournalBookmarkFill;
      case .famicons_journal:
        return Assets.logos.famiconsJournal.assets.famiconsJournal;
      case .fluent_animal_cat_24_filled:
        return Assets.logos.fluentAnimalCat24Filled.assets.fluentAnimalCat24Filled;
      case .iconoir_journal:
        return Assets.logos.iconoirJournal.assets.iconoirJournal;
      case .mdi_fruit_grapes:
        return Assets.logos.mdiFruitGrapes.assets.mdiFruitGrapes;
      case .mingcute_apple_fruit_fill:
        return Assets.logos.mingcuteAppleFruitFill.assets.mingcuteAppleFruitFill;
      case .ooui_journal_ltr:
        return Assets.logos.oouiJournalLtr.assets.oouiJournalLtr;
      case .streamline_ultimate_fruit_banana:
        return Assets.logos.streamlineUltimateFruitBanana.assets.streamlineUltimateFruitBanana;
      case .uil_diary_alt:
        return Assets.logos.uilDiaryAlt.assets.uilDiaryAlt;
    }
  }
}
